sudo: required
services:
  - docker
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE recipes;' -U postgres
  - psql -c "CREATE USER travis_recipes WITH PASSWORD 'travis_recipes';" -U postgres
  - psql -c 'ALTER DATABASE recipes OWNER TO travis_recipes;' -U postgres
  - psql -h localhost -U travis_recipes -d recipes -l

script:
  - docker-compose -f docker-compose-travis.yml run golang make test
  - docker-compose -f docker-compose-travis.yml run golang make coverage
  - docker-compose down

after_success:
  - bash <(curl -s https://codecov.io/bash)
