sudo: required
services:
  - docker
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE recipes;' -U postgres
  - psql -c 'CREATE ROLE dbowner NOLOGIN;' -U postgres
  - psql -c 'ALTER DATABASE recipes OWNER TO dbowner;' -U postgres
  - psql -c "CREATE USER travis_recipes WITH PASSWORD 'travis_recipes';" -U postgres
  - psql -c 'GRANT dbowner TO travis_recipes;' -U postgres

script:
  - docker-compose -f docker-compose-travis.yml run golang make test
  - docker-compose -f docker-compose-travis.yml run golang make coverage
  - docker-compose down

after_success:
  - bash <(curl -s https://codecov.io/bash)
