sudo: required
services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop

script:
  - docker-compose up -d postgres
  - docker-compose run golang make test
  - docker-compose run golang make coverage
  - docker-compose down

after_success:
  - bash <(curl -s https://codecov.io/bash)
