sudo: required
services:
  - docker
  - postgresql

script:
  - docker-compose run golang make test
  - docker-compose run golang make coverage
  - docker-compose down

after_success:
  - bash <(curl -s https://codecov.io/bash)
