version: '2'

networks:
  recipes:

services:

    golang:
        build: .
        image: mramshaw4docs/golang-alpine:1.10.1
        networks:
          recipes:
        depends_on:
            - postgres
        ports:
            - "80:8080"
        volumes:
            - ./src/application:/go/src/application
            - ./src/recipes:/go/src/recipes
            - ./src/test:/go/src/test
            - ./src:/go/src/RestfulRecipes
        working_dir: /go/src/RestfulRecipes
        command: make
        #command: ./restful_recipes
        links:
            - postgres
        environment:
            DEBUG: 'true'
            PORT: '8080'
            POSTGRES_HOST: postgres-backend
            POSTGRES_USER: recipe_user
            POSTGRES_PASSWORD: passw0rd
            POSTGRES_DB: rrecipes

    postgres:
        image: onjin/alpine-postgres:9.5
        networks:
          recipes:
            aliases:
              - postgres-backend
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: recipe_user
            POSTGRES_PASSWORD: passw0rd
            POSTGRES_DB: rrecipes
