# Essentially a copy of 'docker-compose.yml' minus the postgres dependency
#     [Travis insists on supplying its own postgres implementation.]

version: '2'

networks:
  recipes:

services:

    golang:
        build: .
        image: mramshaw4docs/golang-alpine:1.8
        networks:
          recipes:
        ports:
            - "80:8080"
        volumes:
            - ./src/application:/go/src/application
            - ./src/recipes:/go/src/recipes
            - ./src/test:/go/src/test
            - ./src:/go/src/RestfulRecipes
        working_dir: /go/src/RestfulRecipes
        command: make
        #command: ./restful_recipes
        environment:
            DEBUG: 'true'
            PORT: '8080'
            POSTGRES_HOST: localhost
            POSTGRES_USER: travis_recipes
            POSTGRES_PASSWORD: travis_recipes
            POSTGRES_DB: recipes
